// Automatically generated by astro-icon
// 4d926d7e16ed7f900f29cb6bbe9138443f35a1024f09c8b7a4fc63bdf1a9a5c2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "header"
		| "projects/bell"
		| "projects/bible-scraper"
		| "projects/gratis-registry"
		| "projects/personal-website"
		| "projects/wedding-website"
		| "social/bluesky"
		| "social/copylink"
		| "social/linkedin"
		| "social/reddit"
		| "social/telegram"
		| "social/threads"
		| "social/whatsapp"
		| "social/x"
		| "ui/cancel-close"
		| "ui/close"
		| "ui/close-bold"
		| "ui/hamburger"
		| "ui/left-arrow"
		| "ui/page-top"
		| "ui/right-arrow";
}