// Automatically generated by astro-icon
// f91c3ca5d6a102d9a0f4d81b7af194a15db30b777872391bf3e5e03220d268cd

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "projects/bell"
		| "projects/bible-scraper"
		| "projects/gratis-registry"
		| "projects/personal-website"
		| "projects/wedding-website"
		| "social/bluesky"
		| "social/copylink"
		| "social/linkedin"
		| "social/reddit"
		| "social/telegram"
		| "social/threads"
		| "social/whatsapp"
		| "social/x"
		| "ui/cancel-close"
		| "ui/close-bold"
		| "ui/left-arrow"
		| "ui/right-arrow";
}