// Automatically generated by astro-icon
// 994f39baa84686959fa559ee901a69b3bbd6ab6413cf9c3841f13a98f7e65b0e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "header"
		| "projects/bell"
		| "projects/bible-scraper"
		| "projects/gratis-registry"
		| "projects/personal-website"
		| "projects/wedding-website"
		| "social/bluesky"
		| "social/copylink"
		| "social/linkedin"
		| "social/reddit"
		| "social/telegram"
		| "social/threads"
		| "social/whatsapp"
		| "social/x"
		| "ui/cancel-close"
		| "ui/close-bold"
		| "ui/left-arrow"
		| "ui/right-arrow";
}